import { Schema } from 'mongoose';

export const FacialFormSchema: Schema = new Schema({
    recommendation: { type: String, required: false },
    groupon: { type: String, required: false },
    business: { type: String, required: false },
    business_yelp: { type: Boolean, required: false },
    business_google: { type: Boolean, required: false },
    business_groupon: { type: Boolean, required: false },
    business_recommendation: { type: Boolean, required: false },
    wearcontact: { type: Boolean, required: false },
    surgery: { type: Boolean, required: false },
    surgerydescribe: { type: String, required: false },
    skincancer: { type: Boolean, required: false },
    dermatitis: { type: Boolean, required: false },
    keloidscarring: { type: Boolean, required: false },
    acne: { type: Boolean, required: false },
    rosacea: { type: Boolean, required: false },
    broken: { type: Boolean, required: false },
    treatment: { type: Boolean, required: false },
    hypo: { type: Boolean, required: false },
    hyperpig: { type: Boolean, required: false },
    burns: { type: Boolean, required: false },
    anycondition: { type: Boolean, required: false },
    anyconditiondescription: { type: String, required: false },
    allergies: { type: Boolean, required: false },
    latexallergies: { type: Boolean, required: false },
    otherallergies: { type: Boolean, required: false },
    otherallergiesdescription: { type: String, required: false },
    prescription: { type: Boolean, required: false },
    prescriptiondescription: { type: String, required: false },
    pregnant: { type: Boolean, required: false },
    technician: { type: Boolean, required: false },
    techniciandescription: { type: String, required: false },
    appointment: { type: String, required: false },
    oftenfacials: { type: String, required: false },
    oftenbody: { type: String, required: false },
    cosmetic: { type: Boolean, required: false },
    finelines: { type: Boolean, required: false },
    wrinkles: { type: Boolean, required: false },
    dull: { type: Boolean, required: false },
    loss: { type: Boolean, required: false },
    dry: { type: Boolean, required: false },
    oily: { type: Boolean, required: false },
    pores: { type: Boolean, required: false },
    redness: { type: Boolean, required: false },
    sensit: { type: Boolean, required: false },
    dark: { type: Boolean, required: false },
    pimples: { type: Boolean, required: false },
    skin: { type: Boolean, required: false },
    other: { type: Boolean, required: false },
    otherextradescription: { type: String, required: false },
    routine: { type: String, required: false },
    cleanser: { type: Boolean, required: false },
    toner: { type: Boolean, required: false },
    moisturizer: { type: Boolean, required: false },
    spf: { type: Boolean, required: false },
    vitamin: { type: Boolean, required: false },
    scrubs: { type: Boolean, required: false },
    speciality: { type: Boolean, required: false },
    mask: { type: Boolean, required: false },
    supplements: { type: Boolean, required: false },
    exercise: { type: Boolean, required: false },
    scar: { type: Boolean, required: false },
    skinsensitive: { type: Boolean, required: false },
    pictures: { type: Boolean, required: false },
    signature: { type: String, required: false },
    parentsConsent: {
      firstname: { type: String, required: true },
      lastname: { type: String, required: true },
      signature: { type: String, required: true },
    },
  },
  { discriminatorKey: 'type' },
);
