
import { BaseFormModel } from './base-form.model';
import { IParentConsent } from '../../interfaces/generics/parent-consent.interface';
import { FACIALFORM_MODEL_NAME } from '../../../../../constants/constants';

export class FacialFormModel extends BaseFormModel {
  recommendation: string;
  groupon: string;
  business: string;
  businessYelp: boolean;
  businessGoogle: boolean;
  businessGroupon: boolean;
  businessClasspass: boolean;
  businessFacebook: boolean;
  businessRecommendation: boolean;
  wearcontact: boolean;
  surgery: boolean;
  surgerydescribe: string;
  skincancer: boolean;
  dermatitis: boolean;
  keloidscarring: boolean;
  acne: boolean;
  rosacea: boolean;
  broken: boolean;
  treatment: boolean;
  hypo: boolean;
  hyperpig: boolean;
  burns: boolean;
  anycondition: boolean;
  anyconditiondescription: string;
  allergies: boolean;
  latexallergies: boolean;
  otherallergies: boolean;
  otherallergiesdescription: string;
  prescription: boolean;
  prescriptiondescription: string;
  pregnant: boolean;
  technician: boolean;
  techniciandescription: string;
  appointment: string;
  oftenfacials: string;
  oftenbody: string;
  cosmetic: boolean;
  finelines: boolean;
  wrinkles: boolean;
  dull: boolean;
  loss: boolean;
  dry: boolean;
  oily: boolean;
  pores: boolean;
  redness: boolean;
  sensit: boolean;
  dark: boolean;
  pimples: boolean;
  skin: boolean;
  other: boolean;
  otherextradescription: string;
  routine: string;
  cleanser: boolean;
  toner: boolean;
  moisturizer: boolean;
  spf: boolean;
  vitamin: boolean;
  scrubs: boolean;
  speciality: boolean;
  mask: boolean;
  supplements: boolean;
  exercise: boolean;
  scar: boolean;
  skinsensitive: boolean;
  pictures: boolean;
  consent: number;
  signature: string;
  parentsConsent?: Partial<IParentConsent>;
  static ModelName = FACIALFORM_MODEL_NAME;
}
