import { DIRECTORY, FLAG_RETENTION, USER_ROLES } from './enums';

export const DIRECTORY_VALUES = [DIRECTORY.LOCAL, DIRECTORY.GOOGLE, DIRECTORY.GROUPON, DIRECTORY.CLASS_PASS];

export const FLAG_RETENTION_VALUES = [FLAG_RETENTION.NORMAL, FLAG_RETENTION.PERSONAL, FLAG_RETENTION.REQUEST];

export const USER_ROLES_VALUES = [
  USER_ROLES.ADMIN,
  USER_ROLES.MANAGER,
  USER_ROLES.FACIAL_THERAPIST,
  USER_ROLES.MASSAGE_THERAPIST,
  USER_ROLES.HAIR_REMOVERS,
];
