import { DIRECTORY, FLAG_RETENTION } from "./enums";

export const DIRECTORY_VALUES = [DIRECTORY.LOCAL, DIRECTORY.GOOGLE, DIRECTORY.GROUPON, DIRECTORY.CLASS_PASS];

export const FLAG_RETENTION_VALUES = [FLAG_RETENTION.NORMAL, FLAG_RETENTION.PERSONAL, FLAG_RETENTION.REQUEST];